# The version of the docker-compose.
version: "3.8"
# Telling docker-compose to build the client and server images and run them in containers.
services:
  nginx:
    image: nginx:latest
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - "client"
      - "server"
    ports:
      - 3000:80
    container_name: reverse-proxy
  client:
    # Telling docker-compose to build the client image using the Dockerfile in the client directory.
    build: ./frontend
    # Giving the container a name.
    container_name: frontend_c

    # Mapping the client directory on the host machine to the /app directory on the container.
    # volumes:
    #   - ./frontend:/app
    #   - ./app/node_modules
    # Allows you to run container in detached mode.
    stdin_open: true
    tty: true
  server:
    # Telling docker-compose to build the client image using the Dockerfile in the server directory.
    build: ./backend
    container_name: backend_c

    # volumes:
    #   - ./:/app
    #   - ./app/node_modules